# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [5]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [7]:
A = np.arange(1, 16).reshape(3,5)

In [9]:
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)

2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [12]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [14]:
A_sub = B - C # Elementwise subtraction.
A_mult = B * C # Elementwise multiplication.
A_mtx = B @ C # Matrix multiplication (by default you should use the @ operator).

print(A_sub)
print()
print(A_mult)
print()
print(A_mtx)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [17]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
B_exp = np.exp(B)
B_min = np.min(B)
B_min_row = np.min(B, axis=1)
B_min_col = np.min(B, axis=0)
B_min_index = np.argmin(B)
B_min_index_row = np.argmin(B, axis=1)
B_sum = np.sum(B)
B_mean_col = np.mean(B, axis=0)
B_median_col = np.median(B, axis=0)
print(B_exp)
print()
print(B_min)
print(B_min_row)
print(B_min_col)
print(B_min_index)
print(B_min_index_row)
print(B_sum)
print(B_mean_col)
print(B_median_col)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [22]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [24]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

##### When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [ ]:
### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [30]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [32]:
for element in A.flat: # By using flat attributes
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [35]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [37]:
b.shape
# a is a 1D array with 30 elements (0-29)
# b is reshaped into a 3D array using the reshape method into 2 blocks (arrays) with 3 rows in each array, 
# since each block must contain 15 elements, so there will be 5 columns, b has the form (2, 3, 5)


(2, 3, 5)

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [44]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [47]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [49]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [5]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
  
    if (isinstance(matrix1, np.ndarray) and isinstance(matrix2, np.ndarray)) != True: # Validate that inputs are numpy.ndarray
        print('Both inputs must be of type numpy.ndarray.')
    
    if operation != ('add') and operation != ('multiply'): # Validate the operation argument
       print("The operation must be either 'add' or 'multiply'.")
    
    if operation == 'add':
        if matrix1.shape != matrix2.shape: # Validate that the matrices have the same size
            print('For addition, both matrices must have the same dimensions.')
        return matrix1 + matrix2
    
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]: # Validate that the matrices can be multiplied (columns of matrix1 == rows of matrix2)
            print('For multiplication, the number of columns in the first matrix must equal the number of rows in the second matrix.')
        return np.dot(matrix1, matrix2)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
    
# Addition
print("Add Result:\n", add_mult_matrices(A, B, 'add'))
    
# Multiply
print("Multiply Result:\n", add_mult_matrices(A, B, 'multiply'))



Add Result:
 [[ 6  8]
 [10 12]]
Multiply Result:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

## Övningsuppgifter 10.1.1
Definiera vektorn:
x = (4, 3)

### (a) Vilken dimension har vektorn x?


In [126]:
import numpy as np

x = np.array([4, 3])  
print("(a) Dimension:", x.ndim)  

(a) Dimension: 1


### (b) Beräkna 5x


In [86]:
b = 5 * x  
print("(b) 5x =", b)

(b) 5x = [20 15]


### (c) Beräkna 3x


In [91]:
c = 3 * x  
print("(c) 3x =", c)

(c) 3x = [12  9]


### (d) Beräkna 5x + 3x

In [93]:
d = 5 * x + 3 * x  
print("(d) 5x + 3x =", d)

(d) 5x + 3x = [32 24]


### (e) Beräkna 8x

In [99]:
e = 8 * x  
print("(e) 8x =", e)

(e) 8x = [32 24]


### (f) Beräkna 4x - x

In [102]:
f = 4 * x - x  
print("(f) 4x - x =", f)

(f) 4x - x = [12  9]


### (g) Beräkna x^T, vad blir den nya dimensionen?

In [128]:
x_2D = x.reshape(1, -1)  # Gör om till 2D-array
x_2D = x_2D.T  # Transponera
print("(g) Transponerad vektor:", x_2D)
print("Dimension av transponerad:", x_2D.ndim)


(g) Transponerad vektor: [[4]
 [3]]
Dimension av transponerad: 2


### (h) Är x + x^T definierat?
Nej, x har dimension (2,) (1D-array), medan x^T har dimension(2, 1). Dimensionerna måste vara lika

### (i) Beräkna  \|\|x\|\|

In [146]:
x_norm = np.linalg.norm(x)  # Beräkna normen
print("(i) ||x|| =", x_norm)


(i) ||x|| = 5.0


## Övningsuppgifter 10.2.1
Definiera matriserna:

In [3]:
import numpy as np
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])


### (a) Beräkna 2A

In [6]:
a = 2 * A
print('(a) 2A =',a)


(a) 2A = [[ 4  2 -2]
 [ 2 -2  2]]


### (b) Beräkna B - 2A 

In [9]:
b = B - 2 * A
print('(b) B - 2A =', b)

(b) B - 2A = [[ 0 -4  3]
 [ 0 -2 -4]]


### (c) Beräkna 3C - 2E

In [12]:
c = 3 * C - 2 * E
print('(c) 3C - 2E =', c)


(c) 3C - 2E = [[ 1  4]
 [ 2 -1]]


### (d) Beräkna 2D - 3C

In [15]:
d = 2 * D - 3 * C
print('(d) 2D - 3C =', d)


(d) 2D - 3C = [[3 2]
 [2 3]]


### (e) Beräkna D^T + 2D

In [18]:
e = D.T + 2 * D
print('(e) D^T + 2D =', e)

(e) D^T + 2D = [[ 9 12]
 [12  9]]


### (f) Beräkna 2C^T - 2D^T

In [21]:
f = 2 * C.T - 2 * D.T
print('(f) 2C^T - 2D^T =', f)

(f) 2C^T - 2D^T = [[-4 -4]
 [-4 -4]]


### (g) Beräkna A^T - B

In [46]:

print('Dimension av A^T:', A.T.shape)
print('Dimension av B:', B.shape)
try:
    g = A.T - B
    print('(g) A^T - B =', g)
except ValueError as e:
    print('Error in (g):', e)

# With some help from ChatGPT...

Dimension av A^T: (3, 2)
Dimension av B: (2, 3)
Error in (g): operands could not be broadcast together with shapes (3,2) (2,3) 


### (h) Beräkna AC
The number of columns in A is not equal to the number of rows in C. AC is not defined

In [53]:
# Kontrollera dimensionerna för A och C
print('Dimension av A:', A.shape)
print('Dimension av C:', C.shape)

Dimension av A: (2, 3)
Dimension av C: (2, 2)


### (i) Beräkna CD

In [56]:
i = np.dot(C, D)
print('(i) CD =', i)

(i) CD = [[11 10]
 [10 11]]


### (j) Beräkna CB

In [63]:
j = np.dot(C, B)
print('(i) CB =', B)

(i) CB = [[ 4 -2  1]
 [ 2 -4 -2]]


### (k) Beräkna CI

In [66]:
k = np.dot(C, I)
print('(k) CI =', k)

(k) CI = [[1 2]
 [2 1]]


### (l) Beräkna AB^T
The number of columns in A is equal to the number of rows in B^T. AB^T is defined

In [72]:
print("Dimension av A:", A.shape)
print("Dimension av B^T:", B.T.shape)

l = np.dot(A, B.T)
print('(l) AB^T =', l)

Dimension av A: (2, 3)
Dimension av B^T: (3, 2)
(l) AB^T = [[5 2]
 [7 4]]


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Uppgift 10.2.2: Definiera matrisen och beräkna AA^T

In [17]:

A = np.array([[2, 3, 4], [5, 4, 1]])
A_T = A.T
AA_T = np.dot(A, A_T)

print('Matris A:', A)
print()
print('Matris A^T:', A_T)
print()
print('Produkten AA^T:', AA_T)



Matris A: [[2 3 4]
 [5 4 1]]

Matris A^T: [[2 5]
 [3 4]
 [4 1]]

Produkten AA^T: [[29 26]
 [26 42]]


\[
x^2 + y^2 = z^2
\]


### Uppgift 10.2.3: Verifiera att \( AB = AC \) men att \( B \neq C \)
AB är lika med AC
np.array_equal() används för att kontrollera om B & C är lika (både element samt dimension)

In [31]:

A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

AB = np.dot(A, B)
AC = np.dot(A, C)

print('Matris AB:', AB)
print()
print('Matris AC:', AC)
print()
are_B_and_C_equal = np.array_equal(B, C)
print('Är B och C lika?:', are_B_and_C_equal)


Matris AB: [[ 4  7]
 [ 8 14]]

Matris AC: [[ 4  7]
 [ 8 14]]

Är B och C lika?: False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

The 'base' attribute checks whether the array is a view or a copy.

This is because v2 is a view of v1. If v2 is changed to 123, the last element of v1 will also be changed

In [72]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [74]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [76]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
